### ISSUE TITLE
Failure in downloading particular video

### ISSUE THREAD

**Issue by kinnairdclan** [xxcodianxx/youtube-dl-web#28]
Video: https://www.youtube.com/watch?v=_ZI_FdTVXpU -- frontend reports failure to query metadata

Error:
INFO:     172.20.0.5:48704 - "GET /meta/_ZI_FdTVXpU HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/user/app/./server.py", line 55, in api_meta
    meta = query_meta(video_id)
  File "/home/user/app/./util/meta.py", line 51, in query_meta
    "likes": data["like_count"],
KeyError: 'like_count'

Please redirect me if this is a yt-dlp issue, thank you!

**Comment by xxcodianxx** [comment]
Thank you for the issue, and sorry for the neglect of the project.
Should be all fixed now.

NOTE: For some videos I've discovered another bug which does not allow its highest quality to be downloaded. Weirdly, Google's servers do not return data sometimes? This does not relate to the Quick download section, but is exclusive to merging. Will investigate.
