### ISSUE TITLE
irst_chunk = await stream.__anext__() # peek first chunk

### ISSUE THREAD

**Issue by StephanotZaf** [xxcodianxx/youtube-dl-web#33]
Traceback (most recent call last):
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/var/www/youtube-dl-api/venv/lib64/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/var/www/youtube-dl-api/server.py", line 23, in api_dl
    first_chunk = await stream.__anext__() # peek first chunk

**Comment by xxcodianxx** [comment]
I appreciate the high effort issue
